name: Publish artifacts

on:
  push:
    tags:
    - v*

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  release-artifacts:
    name: Save artifacts
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker-image:
    name: Push Docker image
    if: github.event_name == 'push' && contains(github.ref, 'v1.1.')
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: gcr.io/pottava/errs:v1.1
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build & Push
      run: |
        docker build --tag "${IMAGE_NAME}" .
        gcloud --quiet auth configure-docker
        docker push "${IMAGE_NAME}"
    timeout-minutes: 10
